import { Page, Locator } from '@playwright/test';

export class Data {

// Common Data
url = 'http://18.119.119.129:3002/value-gap-analysis-tool';
accessbutton = 'Access Reports';
savebutton = 'Save Progress';
report_name = 'Value Gap Analysis';
nextbutton = 'Next';
backbutton = 'Back';
moredetailsbutton = 'More Details';
hidedetailsbutton = 'Hide Details';
agreeandstart = 'Agree and Start';
yesbutton = 'Yes';
nobutton = 'No';
no_options_selected = 'Choose an option that applies to you';

// Save Progress Section
loginbutton = 'Login';
registerbutton = 'Register';
savereportbutton = 'Save Progress';
reporttype = 'Value Gap Analysis';

// Homescreen Section
homeheader = 'Determine If You Can Fund Your Post-Exit Plans';
homeparagraph = 'Identify the difference between your estimated business value and the amount that may be required to support your desired post-transition lifestyle. This structured eye-opening exercise will incorporate the value-estimate, transition costs and taxes, owner\'s perks, and non-business income and expenses into the analysis.';
beginhere  = 'BEGIN HERE';

// Introduction Section
urlIntro = 'http://18.119.119.129:3002/value-gap-analysis-tool/introduction';
introheader = 'Mind Your Gaps!';
introparag1 = 'The Value Gap is a simple yet often overlooked concept in business transitions. It represents the difference between the amount an owner needs to achieve their post- transition goals and the value they can realisitically obtain for their company through a transition. In essence, it determines whether you can afford your preferred exit path and helps identify the optimal strategy.';
introparag2 = 'This analysis considers the owner\'s personal financial situation, including non-business income streams or personal assets that may contribute to their goals. While we typically assume the owner intends to maintain their current lifestyle, this may not always be the case. Regardless, the exercise remains essential.';
introparag3 = 'Without conducting this guided deep-dive, an owner risks future financial disappointment (or even failure) without realizing it. This often happens because owners';
introlist1 = 'Lack a realistic understanding of their company\'s value.';
introlist2 = 'Fail to properly calculate their likely net proceeds from a transition, such as accounting for capital gains taxes, legal fees, M&A advisory fees, and other deal-related expenses.';
introlist3 = 'Are unfamiliar with common M&A concepts like escrows, holdbacks, contingency payments, and lock-up periods, all of which can impact post-transition proceeds.';
introlist4 = 'Overlook pre-tax expenses previously covered by the company, which they will now have to cover personally on more costly, post-tax basis.';

//Commitment Section
urlcommitment = 'http://18.119.119.129:3002/value-gap-analysis-tool/commitment';
commitment = 'Our Commitment to You';
commitparag1 = 'This tool is designed to provide owners and their trusted advisors with invaluable insights. For best results, a candid self-assessment is necessary, which requires taking an honest look at both yourself and your company.'
commitparag2 = 'We recognize that the data required for this tool is highly sensitive. Rest assured, your inputs and results will remain 100% confidential. You have the option to securely store your data by creating an account with any preferred email address. If you choose to share your information, we will only access it with your explicit permission.'
commitparag3 = 'Creating an account is optional but offers several benefits. It allows you to revisit and update your information periodically, seek technical assistance, and receive feedback. Additionally, it streamlines the process if you choose to use our other tools, as they integrate seamlessly with this one, which will save you or your advisor time.'
commitparag4 = 'The tool also enables you to access and review prior inputs in future years, simplifying annual or periodic updates.'
commitparag5 = 'You will be asked to input specific data and answer up to 17 questions. There will be opportunities to answer additional questions so we can provide further insights that are related to the exercise.'

commitgeninfo = 'General Information';
commitgeninfo_parag1 = 'The report generated by this calculator is for informational purposes only and does not constitute legal, tax, or financial advice. The content is general in nature and should not be relied upon as a substitute for professional consultation. For guidance specific to your situation, please consult a qualified attorney, tax advisor, or financial professional.';
commitgeninfo_parag2 = 'This tool is not intended to provide advisory services or imply that our firm is qualified to offer guidance in all areas of professional services. The report contains data that requires input and evaluation from multiple qualified advisors to ensure accuracy and applicability. We are happy to connect you with the appropriate resources for specialized expertise.'
commitgeninfo_parag3 = 'This tool is an automated, opt-in exercise. Any examples included are intentionally simplified for illustration purposes and do not reflect the full complexity of the topics covered.';

commitnotaxadvice = 'No Tax Advice';
commitnotaxadvice_parag = 'The information contained in the tool’s report is not tax advice and should not be interpreted as such. Tax consequences vary based on individual circumstances and should be assessed by a qualified tax professional. We strongly recommend consulting a tax advisor to evaluate the implications of any strategies or techniques referenced in this report. Each tax strategy carries varying levels of risk, which should be carefully considered with professional guidance.';

commitnofinancialadvice = 'No Financial Advice';
commitnofinancialadvice_parag = 'The results and report of our tool also do not constitute personal or business financial advice. The strategies and concepts discussed should be reviewed with a licensed financial professional to determine their suitability for your specific financial goals and circumstances.';

commitnolegaladvice = 'No Legal Advice';
commitnolegaladvice_parag = 'We are not licensed to provide legal counsel. Nothing in this tool or its report should be interpreted as legal advice. Before making any legal decisions, you should seek the guidance of an attorney licensed in your jurisdiction who can assess your specific situation.';

commitnoopinionofvalue = 'No Opinion of Value';
commitnoopinionofvalue_parag = 'The information provided by this tool does not constitute a formal valuation or an opinion of value for any business or asset. Any valuation figures presented are estimates and do not guarantee the price at which a business or its interests may be sold. For a precise valuation, we recommend consulting a credentialed valuation specialist or appraiser to obtain a certified business valuation.';

commityourcommitmenttous = 'Your Commitment to Us';
commityourcommitmenttous_parag = 'By agreeing and proceeding below, you acknowledge that Exit On Your Terms is not licensed to act, nor is it attempting to act as a subject matter expert, and it will be held harmless in any matters that arise from this tool’s usage or results. You further agree that this tool and its results will not be relied upon for decision-making purposes. Its sole purpose is to help raise awareness around the subject matter and inspire early conversations with an appropriately licensed professional advisor who possesses subject matter expertise.';

committermsnandconditions = 'I agree that I have read and understand the above disclosures, including that this tool is for informational purposes only, does not provide legal, tax, or financial advice, and does not offer a formal opinion of value. I further acknowledge that I will not rely on its results for decision-making and will hold Exit On Your Terms harmless from any matters arising from the tool’s usage or outcomes.';


// Questionnaire Section 1
urlQuestionnaire1 = 'http://18.119.119.129:3002/value-gap-analysis-tool/company-information/1';
Q1 = 'Without a liquidity event, are you confident that you can fund your retirement?';
Q1tooltipmessage = 'Assess whether you could transition away from your business today without relying on its value to support your financial plans. Consider your personal savings, investments, and other income streams as the foundation for financial security after transitioning. ';
Q1tooltipmessage2 = 'Click “Yes” if your personal financial resources are sufficient to support your post-transition plans without relying on the business’s value.';
Q1tooltipmessage3 = 'Click “No” if you would need to sell the business or see its value grow to meet your financial goals.';
Q1tooltipmessage4 = 'Your answer serves as a starting point for understanding whether your current financial resources are enough or if further planning is needed to achieve your post-transition goals.';


// Questionnaire Section 2
urlQuestionnaire2 = 'http://18.119.119.129:3002/value-gap-analysis-tool/company-information/2';

// Questionnaire Section 3
urlQuestionnaire3 = 'http://18.119.119.129:3002/value-gap-analysis-tool/company-information/3';

// Questionnaire Section 4
urlQuestionnaire4 = 'http://18.119.119.129:3002/value-gap-analysis-tool/company-information/4';

// Questionnaire Section 5
urlQuestionnaire5 = 'http://18.119.119.129:3002/value-gap-analysis-tool/company-information/5';

// Questionnaire Section 6
urlQuestionnaire6 = 'http://18.119.119.129:3002/value-gap-analysis-tool/company-information/6';

// Questionnaire Section 6/No
urlQuestionnaire6no = 'http://18.119.119.129:3002/value-gap-analysis-tool/company-information/6/No';

// Questionnaire Section 6/Yes
urlQuestionnaire6yes = 'http://18.119.119.129:3002/value-gap-analysis-tool/company-information/6/Yes';

// Questionnaire Section 7
urlQuestionnaire7 = 'http://18.119.119.129:3002/value-gap-analysis-tool/company-information/7';

// Questionnaire Section 8
urlQuestionnaire8 = 'http://18.119.119.129:3002/value-gap-analysis-tool/company-information/8';

// Questionnaire Section 9
urlQuestionnaire9 = 'http://18.119.119.129:3002/value-gap-analysis-tool/company-information/9';

// Questionnaire Section 10
urlQuestionnaire10 = 'http://18.119.119.129:3002/value-gap-analysis-tool/company-information/10';

// Questionnaire Section 11
urlQuestionnaire11 = 'http://18.119.119.129:3002/value-gap-analysis-tool/company-information/11';

// Questionnaire Section 12
urlQuestionnaire12 = 'http://18.119.119.129:3002/value-gap-analysis-tool/company-information/12';

// Questionnaire Section 13/Popup
urlQuestionnaire13 = 'http://18.119.119.129:3002/value-gap-analysis-tool/discretionary-expenses/13';

// Questionnaire Section 14
urlQuestionnaire14 = 'http://18.119.119.129:3002/value-gap-analysis-tool/discretionary-expenses/14';

// Questionnaire Section 15
urlQuestionnaire15 = 'http://18.119.119.129:3002/value-gap-analysis-tool/discretionary-expenses/15';

// Questionnaire Section 16
urlQuestionnaire16 = 'http://18.119.119.129:3002/value-gap-analysis-tool/discretionary-expenses/16';

// Questionnaire Section 17
urlQuestionnaire17 = 'http://18.119.119.129:3002/value-gap-analysis-tool/discretionary-expenses/17';

// Questionnaire Section 18
urlQuestionnaire18 = 'http://18.119.119.129:3002/value-gap-analysis-tool/discretionary-expenses/18';

// Questionnaire Section 19
urlQuestionnaire19 = 'http://18.119.119.129:3002/value-gap-analysis-tool/discretionary-expenses/19';

// Questionnaire Section 20
urlQuestionnaire20 = 'http://18.119.119.129:3002/value-gap-analysis-tool/discretionary-expenses/20';

// Questionnaire Section 21
urlQuestionnaire21 = 'http://18.119.119.129:3002/value-gap-analysis-tool/discretionary-expenses/21';

// Questionnaire Section 22
urlQuestionnaire22 = 'http://18.119.119.129:3002/value-gap-analysis-tool/discretionary-expenses/22';

// Questionnaire Section 23
urlQuestionnaire23 = 'http://18.119.119.129:3002/value-gap-analysis-tool/discretionary-expenses/23';

// Questionnaire Section 24
urlQuestionnaire24 = 'http://18.119.119.129:3002/value-gap-analysis-tool/discretionary-expenses/24';

// Questionnaire Section 25
urlQuestionnaire25 = 'http://18.119.119.129:3002/value-gap-analysis-tool/discretionary-expenses/25';

// Questionnaire Section 26
urlQuestionnaire26 = 'http://18.119.119.129:3002/value-gap-analysis-tool/discretionary-expenses/26';

// Questionnaire Section 27
urlQuestionnaire27 = 'http://18.119.119.129:3002/value-gap-analysis-tool/discretionary-expenses/27';

// Questionnaire Section 28
urlQuestionnaire28 = 'http://18.119.119.129:3002/value-gap-analysis-tool/discretionary-expenses/28';

// Questionnaire Section 29
urlQuestionnaire29 = 'http://18.119.119.129:3002/value-gap-analysis-tool/discretionary-expenses/29';

// Questionnaire Section 30
urlQuestionnaire30 = 'http://18.119.119.129:3002/value-gap-analysis-tool/discretionary-expenses/30';

// Questionnaire Section 31
urlQuestionnaire31 = 'http://18.119.119.129:3002/value-gap-analysis-tool/discretionary-expenses/31';

// Questionnaire Section 32
urlQuestionnaire32 = 'http://18.119.119.129:3002/value-gap-analysis-tool/additional-income/32';

// Questionnaire Section 33
urlQuestionnaire33 = 'http://18.119.119.129:3002/value-gap-analysis-tool/additional-income/33';

// Questionnaire Section 34
urlQuestionnaire34 = 'http://18.119.119.129:3002/value-gap-analysis-tool/additional-income/34';

// Questionnaire Section 35
urlQuestionnaire35 = 'http://18.119.119.129:3002/value-gap-analysis-tool/additional-income/35';

// Questionnaire Section 36
urlQuestionnaire36 = 'http://18.119.119.129:3002/value-gap-analysis-tool/additional-income/36';

// Questionnaire Section 37
urlQuestionnaire37 = 'http://18.119.119.129:3002/value-gap-analysis-tool/additional-income/37';

// Questionnaire Section 38
urlQuestionnaire38 = 'http://18.119.119.129:3002/value-gap-analysis-tool/additional-income/38';

// Questionnaire Section 39
urlQuestionnaire39 = 'http://18.119.119.129:3002/value-gap-analysis-tool/additional-income/39';

// Questionnaire Section 40
urlQuestionnaire40 = 'http://18.119.119.129:3002/value-gap-analysis-tool/additional-income/40';

// Questionnaire Section 41
urlQuestionnaire41 = 'http://18.119.119.129:3002/value-gap-analysis-tool/additional-income/41'; 

// Questionnaire Section 42
urlQuestionnaire42 = 'http://18.119.119.129:3002/value-gap-analysis-tool/additional-income/42';

// Questionnaire Section 43
urlQuestionnaire43 = 'http://18.119.119.129:3002/value-gap-analysis-tool/additional-income/43';

// Questionnaire Section 44
urlQuestionnaire44 = 'http://18.119.119.129:3002/value-gap-analysis-tool/additional-income/44';

// Questionnaire Section 45
urlQuestionnaire45 = 'http://18.119.119.129:3002/value-gap-analysis-tool/additional-income/45';

// Questionnaire Section 46
urlQuestionnaire46 = 'http://18.119.119.129:3002/value-gap-analysis-tool/additional-income/46';

// Input Review Section
urlInputReview = 'http://18.119.119.129:3002/value-gap-analysis-tool/input-review';

// Net Worth Allocation Section
urlNetWorthAllocation = 'http://18.119.119.129:3002/value-gap-analysis-tool/net-worth-allocation';

// Customize Report Section 1
urlCustomizeReport1 = 'http://18.119.119.129:3002/value-gap-analysis-tool/customize-report-1';

// Customize Report Section 2 (Company Logo)
urlCustomizeReport2 = 'http://18.119.119.129:3002/value-gap-analysis-tool/company-logo';

// Summary Report Section
urlSummaryReport = 'http://18.119.119.129:3002/value-gap-analysis-tool/summary';

// Dashboard Section
urlDashboard = 'http://18.119.119.129:3004/dashboard/companies';


}